### ISSUE TITLE
how do I use extension without importing twin.macro? 

### ISSUE THREAD

**Issue by youngkyo0504** [lightyen/vscode-tailwindcss-twin#33] opened 2022-04-06 01:55 UTC
I use [babel-plugin-twin](https://github.com/ben-rogerson/babel-plugin-twin) to automatically add the tw prop from twin.macro. 
Because I deduct import statement , extension is setted unactive. How do I solve it??

**Comment by lightyen** [comment] 2022-04-06 04:39
Duplicate of #6

**Closed by lightyen** 2022-04-06 04:39 UTC
